# permissions for end users to edit istiogwcerts.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: istiogwcert-editor-role
rules:
- apiGroups:
  - ops.istio.southbridge.io
  resources:
  - istiogwcerts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ops.istio.southbridge.io
  resources:
  - istiogwcerts/status
  verbs:
  - get
