apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: {{ .Chart.Name }}
    app.kubernetes.io/instance: leader-election-rolebinding
    app.kubernetes.io/managed-by: {{ .Chart.Name }}
    app.kubernetes.io/name: rolebinding
    app.kubernetes.io/part-of: {{ .Chart.Name }}
  name: operatorsdk-leader-election-rolebinding
  namespace: {{ .Release.Namespace | quote }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: operatorsdk-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ .Chart.Name }}
  namespace: {{ .Release.Namespace | quote }}