apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operatorsdk-manager-role
rules:
- apiGroups:
  - networking.istio.io
  resources:
  - gateways
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cert-manager.io
  resources:
  - certificates
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ops.istio.southbridge.io
  resources:
  - istiogwcerts
  - istiogwcerts/status
  - istiogwcerts/finalizers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
