apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: kube-rbac-proxy
    app.kubernetes.io/created-by: {{ .Chart.Name }}
    app.kubernetes.io/instance: metrics-reader
    app.kubernetes.io/managed-by: {{ .Chart.Name }}
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/part-of: {{ .Chart.Name }}
  name: operatorsdk-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
