apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: {{ .Chart.Name }}
    app.kubernetes.io/instance: controller-manager-sa
    app.kubernetes.io/managed-by: {{ .Chart.Name }}
    app.kubernetes.io/name: serviceaccount
    app.kubernetes.io/part-of: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
  namespace: {{ .Values.namespace }}

